# Generated by Django 4.2.5 on 2025-08-16 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('subscription_type', models.CharField(choices=[('STARTER', 'Starter'), ('STANDARD', 'Standard'), ('PREMIUM', 'Premium')], default='STARTER', max_length=10)),
                ('container_name', models.CharField(max_length=250)),
                ('storage_quota_bytes', models.BigIntegerField()),
                ('storage_used_bytes', models.BigIntegerField()),
                ('dob', models.DateField(blank=True, null=True)),
                ('email_id', models.EmailField(blank=True, max_length=254, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Blob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blob_id', models.SlugField(editable=False, max_length=32, unique=True)),
                ('blob_name', models.CharField(editable=False, max_length=250, unique=True)),
                ('blob_size', models.BigIntegerField()),
                ('creation_time', models.DateTimeField(blank=True)),
                ('last_modification_time', models.DateTimeField(blank=True)),
                ('blob_type', models.CharField(max_length=50)),
                ('sharing_enabled', models.BooleanField(default=False)),
                ('is_in_directory', models.BooleanField(default=False)),
                ('directory_id', models.SlugField(blank=True, max_length=32, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
