# Generated by Django 4.2.5 on 2025-08-16 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sharing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.SlugField(editable=False, max_length=32, unique=True)),
                ('global_access', models.BooleanField(default=False)),
                ('access_level', models.CharField(choices=[('READ', 'Read'), ('WRITE', 'Write')], default='READ', max_length=36)),
                ('access_scope', models.CharField(choices=[('USER', 'User'), ('GROUP', 'Group'), ('PUBLIC', 'Public')], default='USER', max_length=36)),
                ('share_end_time', models.DateTimeField(blank=True, null=True)),
                ('sharing_link', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='blob',
            name='blob_name',
            field=models.CharField(editable=False, max_length=1024, unique=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='subscription_type',
            field=models.CharField(choices=[('STARTER', 'Starter'), ('STANDARD', 'Standard'), ('PREMIUM', 'Premium')], default='STARTER', max_length=36),
        ),
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directory_id', models.SlugField(editable=False, max_length=32, unique=True)),
                ('directory_name', models.CharField(editable=False, max_length=1024, unique=True)),
                ('creation_time', models.DateTimeField(blank=True)),
                ('last_modification_time', models.DateTimeField(blank=True)),
                ('is_sharing', models.BooleanField(default=False)),
                ('parent_directory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.directory')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
