# Generated by Django 4.2.5 on 2025-08-16 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_sharing_alter_blob_blob_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blob',
            name='blob_id',
            field=models.SlugField(editable=False, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='directory',
            name='directory_id',
            field=models.SlugField(editable=False, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='sharing',
            name='object_id',
            field=models.SlugField(editable=False, max_length=12, unique=True),
        ),
    ]
