# Generated by Django 4.2.5 on 2025-08-16 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_blob_blob_id_alter_directory_directory_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='storage_quota_bytes',
            field=models.BigIntegerField(default=1073741824),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='subscription_type',
            field=models.CharField(choices=[('TESTER', 'Tester'), ('STARTER', 'Starter'), ('STANDARD', 'Standard'), ('PREMIUM', 'Premium'), ('PREMIUM_PLUS', 'PremiumPlus'), ('OWNER', 'Owner')], default='TESTER', max_length=36),
        ),
    ]
