# Generated by Django 4.2.5 on 2025-08-16 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_userinfo_storage_quota_bytes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='storage_quota_bytes',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='subscription_type',
            field=models.CharField(choices=[('TESTER', 'Tester'), ('STARTER', 'Starter'), ('STANDARD', 'Standard'), ('PREMIUM', 'Premium'), ('PREMIUM_PLUS', 'PremiumPlus'), ('OWNER', 'Owner')], default='STARTER', max_length=36),
        ),
    ]
