# Generated by Django 4.2.5 on 2025-08-16 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_userinfo_storage_quota_bytes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='storage_used_bytes',
            field=models.BigIntegerField(default=0),
        ),
    ]
