# Generated by Django 4.2.5 on 2025-08-16 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_userinfo_storage_used_bytes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='container_name',
            field=models.CharField(default='default-container', max_length=250),
        ),
    ]
