# Generated by Django 4.2.5 on 2025-08-16 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_userinfo_container_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blob',
            name='blob_type',
            field=models.CharField(default='file', max_length=50),
        ),
    ]
