# Generated by Django 4.2.5 on 2025-08-16 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_blob_blob_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blob',
            name='blob_name',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='blob',
            name='blob_size',
            field=models.BigIntegerField(default=0),
        ),
    ]
