# Generated by Django 4.2.5 on 2025-08-16 19:13

from django.db import migrations, models
import time


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_blob_blob_name_alter_blob_blob_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blob',
            name='creation_time',
            field=models.FloatField(blank=True, default=time.time),
        ),
        migrations.AlterField(
            model_name='blob',
            name='last_modification_time',
            field=models.FloatField(blank=True, default=time.time),
        ),
    ]
