# Generated by Django 4.2.5 on 2025-08-17 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_blob_creation_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='container_name',
            field=models.CharField(default='None', max_length=250),
        ),
    ]
