# Generated by Django 4.2.5 on 2025-08-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_userinfo_container_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blob',
            name='blob_name',
            field=models.CharField(max_length=1024, unique=True),
        ),
    ]
