# Generated by Django 4.2.5 on 2025-09-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_blob_blob_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='avatar_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
