# Generated by Django 4.2.5 on 2025-09-28 18:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_signuprequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendinguser',
            name='last_sent_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='pendinguser',
            name='otp_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pendinguser',
            name='resend_count',
            field=models.IntegerField(default=1),
        ),
    ]
