# Generated by Django 4.2.5 on 2025-09-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_pendinguser_last_sent_at_pendinguser_otp_attempts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='container_name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
