# Generated by Django 4.2.5 on 2025-11-02 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0020_loginotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='email_id',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='UploadSession',
            fields=[
                ('upload_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('blob_name', models.CharField(max_length=1024)),
                ('total_size', models.BigIntegerField()),
                ('uploaded_size', models.BigIntegerField(default=0)),
                ('uploaded_blocks', models.JSONField(default=list)),
                ('container_name', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'created_at'], name='main_upload_user_id_38e700_idx'), models.Index(fields=['last_activity'], name='main_upload_last_ac_938449_idx')],
            },
        ),
    ]
