# Generated by Django 4.2.5 on 2025-10-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_loginotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='email_id',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
